### ISSUE TITLE
When will digits surport tensorflow and mxnet?

### ISSUE THREAD

**Issue by IvyGongoogle** [NVIDIA/DIGITS#967] opened 2016-08-10 01:41 UTC
I know tensorflow and mxnet can supoort multiple GPUs and multiple machines, but caffe only support multiple GPUs by now. And the speed of tensorflow and mxnet is faster than caffe and torch. So I suggest digits would do this and it will be very nice.

**Comment by lukeyeager** [comment] 2016-08-10 20:43
We have no plans to add support for more frameworks at this time. 

It seems you're interested in other frameworks only for their multi-node capabilities? Do you have any other reasons for wanting to use those particular frameworks?

**Comment by SevenGong** [comment] 2016-08-11 01:58
@lukeyeager I want to train some models much faster,  because some ConvNets are very deep. So choosing a faster framework is good choice such as mxnet and tensorflow, and they just support  multiple machines. So it seems to be very exciting if digits support  mxnet and tensorflow.

**Comment by SevenGong** [comment] 2016-08-12 08:14
@lukeyeager cntk is also a very good framwork.

**Comment by TimZaman** [comment] 2016-08-29 11:46
I've got a branch that supports tensorflow in Digits for classification: https://github.com/brainstorm-ai/DIGITS/tree/tensorflow
I'll update this into a PR only when Tensorflow hits 1.0 . Currently the bottleneck is with proper dataloading. I am currently using TF placeholders, which is inefficient and so not suitable for production or anything professional imo. I need to make a LMDB dataloader to put along the TF graph properly in C++. With my PR i have been able to reproduce identical MNIST results in DIGITS with TF compared to Caffe and Torch. 
So I am planning on picking up TF more when TF reaches 1.0, however, DIGITS is expanding so quickly that with every framework it supports it will yield ever more work, making DIGITS's feature development less lean.

**Comment by gheinrich** [comment] 2016-08-29 20:38
That sounds fantastic! Out of curiosity, did you consider Keras as an intermediate layer between DIGITS and Tensorflow? It's less flexible but more focused on Deep Learning than the raw Tensorflow. I was thinking that it could be easier to interface with.

**Comment by TimZaman** [comment] 2016-08-29 20:49
I'm not a fan of the abstraction layers, especially from another party. I was really hoping for 'Tensorflow Slim' to be included in the TensorFlow main brain. And it did end up there. Tensorflow-slim is a really nice 'wrapper' that you will recognize is very torchy.

Note that for the implementation of writing models I have stolen your torch implementation with models @gheinrich ; 
i.e.
```py
def build_model(params):
    # build model here with $params
    return {
        model: $model
     }
```

As you can see below, your comment is very valid. You don't want to mess with raw TF. Even the slightest typo will ruin your ~day~ weekend.

<h3>LeNet with TF-Slim</h3>
https://github.com/brainstorm-ai/DIGITS/blob/tensorflow/digits/standard-networks/tensorflow/lenet_slim.py
```py
model = slim.ops.conv2d(_x, 20, [5, 5], stddev=1/math.sqrt(5*5*params['input_shape'][2]), padding='VALID', scope='conv1')
model = slim.ops.max_pool(model, [2, 2], padding='VALID', scope='pool1')
model = slim.ops.conv2d(model, 50, [5, 5], stddev=1/math.sqrt(5*5*20), padding='VALID', scope='conv2')
model = slim.ops.max_pool(model, [2, 2], padding='VALID', scope='pool2')
model = slim.ops.flatten(model)
model = slim.ops.fc(model, 500, stddev=1/math.sqrt(4*4*50), scope='fc1')
model = tf.nn.relu(model, name='relu')
model = slim.ops.dropout(model, 0.75, scope='do1')
model = slim.ops.fc(model, params['nclasses'], stddev=1/math.sqrt(500), activation=None, scope='fc2')
```

<h3>LeNet with raw TF</h3>
https://github.com/brainstorm-ai/DIGITS/blob/tensorflow/digits/standard-networks/tensorflow/lenet.py
```py
  # Create some wrappers for simplicity
    def conv2d(x, W, b, strides=1):
        # Conv2D wrapper, with bias and relu activation
        x = tf.nn.conv2d(x, W, strides=[1, strides, strides, 1], padding='VALID')
        x = tf.nn.bias_add(x, b)
        return tf.nn.relu(x)

    def maxpool2d(x, k=2):
        # MaxPool2D wrapper
        return tf.nn.max_pool(x, ksize=[1, k, k, 1], strides=[1, k, k, 1], padding='VALID')

    # Create model
    def conv_net(x, weights, biases, dropout):
        # Reshape input picture
        x = tf.reshape(x, shape=[-1, params['input_shape'][0], params['input_shape'][1], params['input_shape'][2]])

        # Convolution Layer
        conv1 = conv2d(x, weights['wc1'], biases['bc1'])
        # Max Pooling (down-sampling)
        conv1 = maxpool2d(conv1, k=2)

        # Convolution Layer
        conv2 = conv2d(conv1, weights['wc2'], biases['bc2'])
        # Max Pooling (down-sampling)
        conv2 = maxpool2d(conv2, k=2)

        # Fully connected layer
        # Reshape conv2 output to fit fully connected layer input
        fc1 = tf.reshape(conv2, [-1, weights['wd1'].get_shape().as_list()[0]])
        fc1 = tf.add(tf.matmul(fc1, weights['wd1']), biases['bd1'])
        fc1 = tf.nn.relu(fc1)
        
        # Apply Dropout
        #fc1 = tf.nn.dropout(fc1, dropout)

        # Output, class prediction
        out = tf.add(tf.matmul(fc1, weights['out']), biases['out'])
        return out


    # Initialize W using stddev 1/sqrt(n), with n the input dimension size.
    # Store layers weight & bias
    weights = {
        # 5x5 conv, 1 input, 20 outputs
        #'wc1': tf.Variable(tf.random_normal([5, 5, params['input_shape'][2], 20], stddev=1/math.sqrt(weight_n['wc1']))),
        'wc1': tf.get_variable('wc1', [5, 5, params['input_shape'][2], 20], initializer=tf.truncated_normal_initializer(stddev=1/math.sqrt(5*5*params['input_shape'][2]))),
        #'wc1': tf.Variable(tf.random_normal([5, 5, params['input_shape'][2], 20], stddev=0.1)),
        # 5x5 conv, 20 inputs, 50 outputs
        'wc2': tf.get_variable('wc2', [5, 5, 20, 50], initializer=tf.truncated_normal_initializer(stddev=1/math.sqrt(5*5*20))),
        #'wc2': tf.Variable(tf.random_normal([5, 5, 20, 50], stddev=1/math.sqrt(weight_n['wc2']))),
        # fully connected, 4*4*16=800 inputs, 500 outputs
        'wd1': tf.get_variable('wd1', [4*4*50, 500], initializer=tf.truncated_normal_initializer(stddev=1/math.sqrt(4*4*50))),
        #'wd1': tf.Variable(tf.random_normal([4*4*50, 500], stddev=1/math.sqrt(weight_n['wd1']))),
        # 500 inputs, 10 outputs (class prediction)
        'out': tf.get_variable('wout', [500, params['nclasses']], initializer=tf.truncated_normal_initializer(stddev=1/math.sqrt(500))),
        #'out': tf.Variable(tf.random_normal([500, params['nclasses']], stddev=1/math.sqrt(weight_n['out'])))
    }

    # Leave the intial biases zero
    biases = {
        'bc1': tf.get_variable('bc1', [20], initializer=tf.constant_initializer(0.0)),
        'bc2': tf.get_variable('bc2', [50], initializer=tf.constant_initializer(0.0)),
        'bd1': tf.get_variable('bd1', [500], initializer=tf.constant_initializer(0.0)),
        'out': tf.get_variable('bout', [params['nclasses']], initializer=tf.constant_initializer(0.0))
    }
```

**Comment by sskgit** [comment] 2017-04-05 16:00
@TimZaman Tensorflow 1.0 is out for some time now and has phenomenal traction. Would be really great to include Tensorflow support in DIGITS.

**Comment by phpmind** [comment] 2017-04-05 23:46
lukeyeager - Tensorflow is very cool. Is that final, that your team is not going to support tensorflow for Digit  ever :)

This is big problem for us!

**Comment by TimZaman** [comment] 2017-04-06 08:45
Feel free to play around with a rough TF-DIGITS using this branch **we (nvidia/digits-team) do not officially support**:
https://github.com/TimZaman/DIGITS/tree/tensorflow

**Comment by phpmind** [comment] 2017-04-06 17:33
Tim - Do we have Docker version of this/ TF-DIGITS ?  I am using docker in windows.  

Thanks

**Comment by IvyGongoogle** [comment] 2017-04-11 14:26
@TimZaman sorry to bother you. I do a test using the command `python _test.py` under `digits/tools/tensorflow` , but it shows error:

```
Traceback (most recent call last):
  File "main.py", line 659, in <module>
    tf.app.run()     
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 537, in main
    Validation(sess, val_model, 0)
  File "main.py", line 358, in Validation
    summary_str = sess.run(model.summary)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [29768,2] and labels shape [128]
	 [[Node: val/loss/cross_entropy_per_example/cross_entropy_per_example = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"](val/model/Add_1, val/data/batcher/_7)]]
	 [[Node: val/loss/loss/_11 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_70_val/loss/loss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'val/loss/cross_entropy_per_example/cross_entropy_per_example', defined at:
  File "main.py", line 659, in <module>
    tf.app.run()
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 478, in main
    val_model.create_model(UserModel, stage_scope)
  File "/home/ztgong/work/digitses/DIGITS-tensorflow-new/digits/tools/tensorflow/model.py", line 141, in create_model
    tf.add_to_collection(digits.GraphKeys.LOSSES, tower_model.loss)
  File "/home/ztgong/work/digitses/DIGITS-tensorflow-new/digits/tools/tensorflow/utils.py", line 34, in decorator
    setattr(self, attribute, function(self))
  File "<string>", line 67, in loss
  File "/home/ztgong/work/digitses/DIGITS-tensorflow-new/digits/tools/tensorflow/utils.py", line 43, in classification_loss
    ssoftmax = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=pred,labels=y, name='cross_entropy_per_example')
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1713, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2378, in _sparse_softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): logits and labels must have the same first dimension, got logits shape [29768,2] and labels shape [128]
	 [[Node: val/loss/cross_entropy_per_example/cross_entropy_per_example = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"](val/model/Add_1, val/data/batcher/_7)]]
	 [[Node: val/loss/loss/_11 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_70_val/loss/loss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

```

how to fix it ? can you give some advices? 
thank you in advance!
my tf is 1.0.1.

**Comment by TimZaman** [comment] 2017-04-11 14:37
Closing this issue, as **we do not support Tensorflow at this time**. Any questions about the experimental branch that was just referred to are not to be discussed here.

**Closed by TimZaman** 2017-04-11 14:37 UTC
Labels: enhancement
