### ISSUE TITLE
Unrecognised Output: CreateDB.py

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#292] opened 2015-09-10 19:41 UTC
Hey guys,

Been crawling around the issues section for a while now and tried pretty much all bugfixes i can get my hands on - but still to no avail. Sorry if this has already been solved - in which case, if you could point me in the right direction and close the thread then awesome.

Attempting to build a new dataset ready for training on our new DL machine we picked up today and DIGITS hangs/crashes in the first 5 seconds of building the set. I've disabled cuDNN, put the caffe into debug mode, updated lmdb, and still, keeps crashing.

We are running a GTX960 btw and also Git Pulled the DIGITS master and caffe 0.13 branch.

PLus, hopefully it helps but here's a output of the log trace:
```
 * Running on http://0.0.0.0:5000/
192.168.0.44 - - [2015-09-11 05:22:26] "GET / HTTP/1.1" 200 9382 0.106556
2015-09-11 05:22:30 [20150911-045818-8887] [INFO ] Job deleted.
192.168.0.44 - - [2015-09-11 05:22:30] "DELETE /jobs/20150911-045818-8887 HTTP/1.1" 200 128 0.003674
192.168.0.44 - - [2015-09-11 05:22:30] "GET / HTTP/1.1" 200 8840 0.010495
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/css/style.css HTTP/1.1" 200 994 0.006967
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/css/bootstrap-theme.min.css HTTP/1.1" 200 19147 0.001697
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/css/c3.min.css HTTP/1.1" 200 2258 0.001608
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/js/bootbox.min.js HTTP/1.1" 200 9025 0.001656
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 32106 0.017304
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/js/digits.js HTTP/1.1" 200 716 0.001452
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/js/jquery-1.11.1.min.js HTTP/1.1" 200 96073 0.038463
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 109808 0.051672
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/js/d3.min.js HTTP/1.1" 200 151414 0.057002
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/js/jquery.autocomplete.min.js HTTP/1.1" 200 13267 0.002362
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/js/socket.io.js HTTP/1.1" 200 100266 0.035723
192.168.0.44 - - [2015-09-11 05:22:30] "GET /static/js/c3.min.js HTTP/1.1" 200 137564 0.097064
192.168.0.44 - - [2015-09-11 05:22:36] "POST /datasets/images/classification HTTP/1.1" 302 454 0.395790
192.168.0.44 - - [2015-09-11 05:22:36] "GET /datasets/20150911-052236-5efa HTTP/1.1" 200 19543 0.082335
2015-09-11 05:22:37 [20150911-052236-5efa] [INFO ] Parse Folder (train/val/test) task started.
2015-09-11 05:22:38 [20150911-052236-5efa] [INFO ] Parse Folder (train/val/test) task completed.
2015-09-11 05:22:38 [20150911-052236-5efa] [INFO ] Create DB (train) task started.
2015-09-11 05:22:38 [20150911-052236-5efa] [INFO ] Create DB (val) task started.
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-4:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-3:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-6:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-7:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-5:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-8:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-2:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-1:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-1:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-4:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-10:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-5:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-8:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-6:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-9:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-10:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-3:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-2:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-7:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: NameError: global name 'e' is not defined
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-9:
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.run()
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 418, in _load_thread
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: logger.warning('[%s] %s: %s' % (path, type(e).__name__, e) )
2015-09-11 05:22:39 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: NameError: global name 'e' is not defined
^CKeyboardInterrupt
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 637, in <module>
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: lmdb_map_size   = args['lmdb_map_size']
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 143, in create_db
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: mean_files, **kwargs)
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 213, in _create_lmdb
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: time.sleep(0.2)
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (train) unrecognized output: KeyboardInterrupt
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 637, in <module>
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: lmdb_map_size   = args['lmdb_map_size']
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 143, in create_db
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: mean_files, **kwargs)
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: File "/home/dev/DIGITS/tools/create_db.py", line 213, in _create_lmdb
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: time.sleep(0.2)
2015-09-11 05:27:17 [20150911-052236-5efa] [WARNING] Create DB (val) unrecognized output: KeyboardInterrupt
2015-09-11 05:27:18 [20150911-052236-5efa] [ERROR] Create DB (train) task failed with error code 1
2015-09-11 05:27:18 [20150911-052236-5efa] [ERROR] Create DB (val) task failed with error code 1
```

**Comment by lukeyeager** [comment] 2015-09-10 21:09
Duplicate of #288.

**Closed by lukeyeager** 2015-09-10 21:09 UTC

**Comment by RadicoLabs** [comment] 2015-09-11 01:14
Thanks Luke - pulled the git fix and it's working again - however, now the logs are showing a crap load of LoadImageError: IOErrors . Can this be ignored or do we have another bug?

**Comment by RadicoLabs** [comment] 2015-09-11 03:29
Fixed, to anyone else having the LoadImageError: IOErrors problem, check your file ownerships... You may not read/write access to them
