### ISSUE TITLE
Why does inference.py load first the whole dataset in memory?

### ISSUE THREAD

**Issue by hahne** [NVIDIA/DIGITS#1368] opened 2017-01-03 17:51 UTC
If I do 'Classify Many' using a big dataset, I get memory issues. The issue is the inference.py first loads all image files into the memory. Is there a way to avoid this behaviour?

**Comment by gheinrich** [comment] 2017-01-03 20:43
Hello, thanks for the report. There was an attempt at fixing this with https://github.com/NVIDIA/DIGITS/pull/616 but this was closed due to other priorities...

I'll close this as a duplicate of #611

**Closed by gheinrich** 2017-01-03 20:43 UTC
