### ISSUE TITLE
Digits 5.1 UI error when access digits from another local system

### ISSUE THREAD

**Issue by Noor59007** [NVIDIA/DIGITS#1267] opened 2016-11-14 05:57 UTC
![screenshot](https://cloud.githubusercontent.com/assets/6708048/20254748/9724c2ec-aa7a-11e6-9640-fe7f33df82c8.png)

**Comment by gheinrich** [comment] 2016-11-14 07:20
Duplicate of #1255

**Closed by gheinrich** 2016-11-14 07:20 UTC
