### ISSUE TITLE
DIGITS UI bug when training object detection?

### ISSUE THREAD

**Issue by kertansul** [NVIDIA/DIGITS#1266] opened 2016-11-14 02:44 UTC
This is what I get while training car detection on KITTI with digits-5.0 

![image](https://cloud.githubusercontent.com/assets/18409971/20251605/7b552b8a-aa55-11e6-9e24-0aa284229b65.png)

The model is actually learning something (as you can see the numbers on "precision", "recall" and "mAP"), but from the chart I get is somewhat misleading (the **lines drawn are far lower than the numbers indicated**)

This bug, however, disappears when I retrained the model ...
I guess this is worth noticing since if someone bumps into the same issue, they might want to **check the numbers precisely rather than just looking at the graph** (like what I previously do..)

**Comment by kertansul** [comment] 2016-11-14 02:57
A quick update (hope that's helpful for debugging)
My loss function contains a peak at the 2nd epoch.

If I zoom in the chart from the 3rd epoch, it's OK
![image](https://cloud.githubusercontent.com/assets/18409971/20251956/d0096ac6-aa58-11e6-9835-2c8e4a8430a4.png)

If the zoom in graph contains that peak, it'll trigger this bug
![image](https://cloud.githubusercontent.com/assets/18409971/20251970/eab72746-aa58-11e6-9779-b853603385da.png)

**Comment by gheinrich** [comment] 2016-11-14 07:11
Hello, you need to use the left axis to read mAP, precision, and recall. closing as duplicate of #900.

**Closed by gheinrich** 2016-11-14 07:11 UTC

**Comment by windSong1** [comment] 2017-01-17 03:27
FFFSDFSFSFSDF# # _FDFSF**FDFDF**_# FDFDSFFDF# FDF
