### ISSUE TITLE
  ERROR: error code -6

### ISSUE THREAD

**Issue by amirahazman** [NVIDIA/DIGITS#1890] opened 2017-11-22 04:41 UTC
After finish the installation, I trained the system but when I tried to run classify one the pictures, I got this error.

WARNING: Logging before InitGoogleLogging() is written to STDERR
E1122 12:29:18.206468  3480 common.cpp:128] Cannot create cuDNN handle. cuDNN won't be available.
F1122 12:29:18.252681  3480 gpu_memory.cpp:152] Check failed: error == cudaSuccess (46 vs. 0)  all CUDA-capable devices are busy or unavailable
*** Check failure stack trace: ***
       
Please help me.

**Comment by shitian-ni** [comment] 2017-11-25 09:53
Probably a duplicate of #1260.

**Comment by amirahazman** [comment] 2017-11-25 14:47
Thanks @shitian-ni for the reply,
i manage to solve the problem by replacing the gpu card with higher compute capability.

**Closed** 2018-04-26 07:36 UTC
