### ISSUE TITLE
Train Caffe Model task failed with error code -6

### ISSUE THREAD

**Issue by samar166** [NVIDIA/DIGITS#1298] opened 2016-11-28 03:18 UTC
I tried to train AlexNet on my dataset with 700 epochs, but I got the error 6 at iteration 681 as follows:
```
Iteration 7540 (6.10624 iter/s, 0.163767s/1 iter), loss = 1.59853e-06
Train net output #0: loss = 1.68384e-06 (* 1 = 1.68384e-06 loss)
Iteration 7540, lr = 0.0001
Iteration 7541 (6.22464 iter/s, 0.160652s/1 iter), loss = 8.30435e-06
Train net output #0: loss = 8.38967e-06 (* 1 = 8.38967e-06 loss)
Iteration 7541, lr = 0.0001
Iteration 7542 (6.4846 iter/s, 0.154212s/1 iter), loss = 1.85298e-05
Train net output #0: loss = 1.86151e-05 (* 1 = 1.86151e-05 loss)
Iteration 7542, lr = 0.0001
Iteration 7543 (6.25333 iter/s, 0.159915s/1 iter), loss = 2.92384e-05
Train net output #0: loss = 2.93237e-05 (* 1 = 2.93237e-05 loss)
Iteration 7543, lr = 0.0001
Iteration 7544 (6.42588 iter/s, 0.155621s/1 iter), loss = 0.000124404
Train net output #0: loss = 0.000124489 (* 1 = 0.000124489 loss)
Iteration 7544, lr = 0.0001
Iteration 7545 (6.19574 iter/s, 0.161401s/1 iter), loss = 1.9483e-05
Train net output #0: loss = 1.95683e-05 (* 1 = 1.95683e-05 loss)
Iteration 7545, lr = 0.0001
Snapshotting to binary proto file snapshot_iter_7546.caffemodel
Check failed: proto.SerializeToOstream(&output)
```
I appreciate it if   anyone can give me some ideas.

**Comment by lukeyeager** [comment] 2016-11-28 17:37
Duplicate of https://github.com/NVIDIA/DIGITS/issues/84. Please reply there if you have any information about how to reproduce the issue.

**Closed by lukeyeager** 2016-11-28 17:37 UTC
