### ISSUE TITLE
Error while trying to visualize network 

### ISSUE THREAD

**Issue by MyAusweis** [NVIDIA/DIGITS#1559] opened 2017-04-04 08:42 UTC
Dear All I wonder why every time i want to visualize network model , the result :
AttributeError : 'int' object has no attribute '_values'

![errorvisualize](https://cloud.githubusercontent.com/assets/7820402/24648254/46077e26-194d-11e7-830f-443005f95070.jpg)

Pls help me

Thx

**Comment by lukeyeager** [comment] 2017-04-04 15:57
Duplicate of https://github.com/NVIDIA/DIGITS/issues/1534.

**Closed by lukeyeager** 2017-04-04 15:57 UTC
Labels: duplicate
