### ISSUE TITLE
loading detectnet_network.prototxt to nvCaffe

### ISSUE THREAD

**Issue by ttheekshanaw** [NVIDIA/DIGITS#1486] opened 2017-03-02 08:23 UTC
I0302 15:19:19.081395 20093 layer_factory.hpp:77] Creating layer deploy_data
I0302 15:19:19.081418 20093 net.cpp:94] Creating Layer deploy_data
I0302 15:19:19.081429 20093 net.cpp:409] deploy_data -> data
I0302 15:19:19.081478 20093 net.cpp:144] Setting up deploy_data
I0302 15:19:19.081496 20093 net.cpp:151] Top shape: 1 3 384 1248 (1437696)
I0302 15:19:19.081503 20093 net.cpp:159] Memory required for data: 5750784
I0302 15:19:19.081512 20093 layer_factory.hpp:77] Creating layer deploy_transform
I0302 15:19:19.081524 20093 net.cpp:94] Creating Layer deploy_transform
I0302 15:19:19.081532 20093 net.cpp:435] deploy_transform <- data
I0302 15:19:19.081544 20093 net.cpp:409] deploy_transform -> transformed_data
I0302 15:19:19.081559 20093 net.cpp:144] Setting up deploy_transform
I0302 15:19:19.081578 20093 net.cpp:151] Top shape: 1 3 384 1248 (1437696)
I0302 15:19:19.081584 20093 net.cpp:159] Memory required for data: 11501568
I0302 15:19:19.081590 20093 layer_factory.hpp:77] Creating layer conv1/7x7_s2
I0302 15:19:19.081607 20093 net.cpp:94] Creating Layer conv1/7x7_s2
I0302 15:19:19.081612 20093 net.cpp:435] conv1/7x7_s2 <- transformed_data
I0302 15:19:19.081621 20093 net.cpp:409] conv1/7x7_s2 -> conv1/7x7_s2
Segmentation fault (core dumped)

It gives this error while loading.

Also i tried loading imagenet. still gives this error. tried the same imagenet.prototxt file with the original caffe from BVLC. It loads the network perfectly.

Any suggestions ?

**Comment by MKYucel** [comment] 2017-03-02 08:39
I think you can get some hints as to what's wrong using gdb or any other tool. It seems you are having problems loading the network itself (so you are still on CPU),  so gdb should point you to the right direction.

**Comment by ttheekshanaw** [comment] 2017-03-02 08:44
nope i am on GPU.

**Comment by MKYucel** [comment] 2017-03-02 08:47
Even if you do inference on GPUs, given your error log, you are still loading the network hence you are on CPU, therefore you should get an answer using gdb.

**Comment by ttheekshanaw** [comment] 2017-03-02 08:49
this is what i got from gdb

received signal SIGSEGV, Segmentation fault.
0x00007ffff69f1d97 in caffe::Caffe::rng_stream() ()
   from /build/lib/libcaffe-nv.so.0.15

**Comment by MKYucel** [comment] 2017-03-02 08:52
[This](https://github.com/BVLC/caffe/issues/3788) could be of help. There are other issues posted on Caffe repository. This is actually related to Caffe, not DIGITS.

**Comment by ttheekshanaw** [comment] 2017-03-02 08:57
#0  0x00007ffff69f1d97 in caffe::Caffe::rng_stream() ()
   from /home/theekshana/Nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#1  0x00007ffff69f96d2 in void caffe::caffe_rng_uniform<float>(int, float, float, float*) ()
   from /home/theekshana/Nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#2  0x00007ffff6a584e9 in caffe::XavierFiller<float>::Fill(caffe::Blob<float>*) ()
   from /home/theekshana/Nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#3  0x00007ffff6b3c04e in caffe::BaseConvolutionLayer<float>::LayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&) () from /home/theekshana/Nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#4  0x00007ffff6b4a3d0 in caffe::CuDNNConvolutionLayer<float>::LayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&) () from /home/theekshana/Nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#5  0x00007ffff6a31962 in caffe::Net<float>::Init(caffe::NetParameter const&) ()
   from /home/theekshana/Nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#6  0x00007ffff6a3395d in caffe::Net<float>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, caffe::Net<float> const*) ()
   from /home/theekshana/Nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#7  0x00000000004045ae in main ()

**Comment by gheinrich** [comment] 2017-03-02 09:26
@ttheekshanaw please be considerate. Don't create duplicate issues.

closing as duplicate of https://github.com/NVIDIA/caffe/issues/296.

**Closed by gheinrich** 2017-03-02 09:26 UTC
