### ISSUE TITLE
test One Image error "500 Internal server error AssertionError "

### ISSUE THREAD

**Issue by Chamunsu** [NVIDIA/DIGITS#112] opened 2015-05-16 07:11 UTC
![error](https://cloud.githubusercontent.com/assets/8610430/7665152/dae71830-fbe5-11e4-89a1-4700bf20597a.PNG)
I run train mnist. 
then I upload mnist image file. 
click Test One image. but here meet the error 
"500 internal server error "
"assertion Error "
"expect blob.data.ndim ==4"

why this problem??

**Comment by lukeyeager** [comment] 2015-05-18 16:22
Make sure you are using the correct version of caffe. From your screenshot, it looks like you are using an older version of the DIGITS software, so I would expect that you need version `0.10.0` of the NVIDIA/caffe fork. See instructions here:

https://github.com/NVIDIA/DIGITS/blob/digits-1.0/README.md#prerequisites

If you **are** already using the correct version, please let me know.

**Comment by Chamunsu** [comment] 2015-05-18 17:59
Thank you. 

I received new 0.11.0 digits. 

this problem solved.

but I have problem classification page. 

I want to customize alexnet. so I click visualize button. 

I meet the error below. 

![err](https://cloud.githubusercontent.com/assets/8610430/7686718/e3f1bd56-fdd2-11e4-893b-84e9b5bf7c2b.PNG)

and I want to use pretraind model. 

Are you can support this part manual??

**Comment by lukeyeager** [comment] 2015-05-18 18:34
This looks like it may be a duplicate of @Pastafarianist's problem: https://github.com/NVIDIA/DIGITS/issues/90#issuecomment-96811119.

See the discussion here: https://github.com/BVLC/caffe/issues/2376. If the same fix solves your problem, I'd mention it in that issue so that caffe can solve this issue on their end.

**Comment by lukeyeager** [comment] 2015-07-06 21:26
This is now fixed in NVIDIA/caffe - https://github.com/NVIDIA/caffe/commit/d854224533bad81049a26ebf495679dccaea6a05. Pull in the latest version of DIGITS and NVIDIA/caffe to get the fix.

FYI, this is also fixed in BVLC/caffe - see https://github.com/BVLC/caffe/pull/2579.

**Closed by lukeyeager** 2015-07-06 21:26 UTC
