### ISSUE TITLE
Object detection KITTI format

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/DIGITS#1039] opened 2016-09-05 11:55 UTC
I wonder are `truncated` and  `occluded` fields of KITTI format used during training? If not what should we do with images that contain such cases, exclude from training set? 

~~~
  1    truncated    Float from 0 (non-truncated) to 1 (truncated), where
                     truncated refers to the object leaving image boundaries
   1    occluded     Integer (0,1,2,3) indicating occlusion state:
                     0 = fully visible, 1 = partly occluded
                     2 = largely occluded, 3 = unknown
~~~

**Comment by gheinrich** [comment] 2016-09-05 23:28
Closing as duplicate of #992

**Closed by gheinrich** 2016-09-05 23:28 UTC
