### ISSUE TITLE
The official NVIDIA model store

### ISSUE THREAD

**Issue by BrainyBeeLy** [NVIDIA/DIGITS#1371] opened 2017-01-05 03:32 UTC
Do it : [(https://github.com/NVIDIA/DIGITS/blob/master/docs/ModelStore.md )]
    Digits5 can not load model from the official NVIDIA moden store.
 ### How to do, next ?
![u6661s u6w4w7i 6 m8ch30](https://cloud.githubusercontent.com/assets/19223638/21668185/5b70b56a-d33a-11e6-98e7-ae37248d2c71.png)

**Comment by gheinrich** [comment] 2017-01-05 09:38
Duplicate of #1214

**Closed by gheinrich** 2017-01-05 09:38 UTC
