### ISSUE TITLE
Where the function 'scheduler/main_thread' is called when I click the button 'create' in module 'new image classification'?

### ISSUE THREAD

**Issue by JulyUp** [NVIDIA/DIGITS#1019] opened 2016-08-30 14:26 UTC
I try my best to trace the code when I click the button 'create' in module 'new image classification'. But I still do not know where the function 'scheduler/main_thread' is called. 

Who can tell me?Looking forward to your response.Thank you very very much.

**Comment by gheinrich** [comment] 2016-08-30 14:28
Duplicate of https://github.com/NVIDIA/DIGITS/issues/979#issuecomment-243444220

Please don't create an issue for every such question. Preferably, use the DIGITS users list on https://groups.google.com/forum/#!forum/digits-users

**Closed by gheinrich** 2016-08-30 14:28 UTC

**Comment by JulyUp** [comment] 2016-08-31 12:15
@gheinrich  Thank you very much. And I am very sorry to bother you so much. 
Thank you.
