### ISSUE TITLE
Ubuntu Installation Guide not working

### ISSUE THREAD

**Issue by jas0n1ee** [NVIDIA/DIGITS#433] opened 2015-11-24 00:55 UTC
I was trying to install digits and caffe using this [guide](https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md), and when I try using following command to download `nvidia-machine-learning-repo_4.0-1_amd64.deb` , it returns a 404 not found error. 
```
ML_REPO_PKG=nvidia-machine-learning-repo_4.0-1_amd64.deb &&
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/$ML_REPO_PKG &&
    sudo dpkg -i $ML_REPO_PKG
```

**Comment by lukeyeager** [comment] 2015-11-24 01:00
Duplicate of https://github.com/NVIDIA/DIGITS/issues/427.

**Closed by lukeyeager** 2015-11-24 01:00 UTC
Labels: duplicate
