### ISSUE TITLE
Error 404 while downloading nvidia-machine-learning-repo_4.0-1_amd64.deb 

### ISSUE THREAD

**Issue by alexeykurov** [NVIDIA/DIGITS#451] opened 2015-12-03 15:24 UTC
ML_REPO_PKG=nvidia-machine-learning-repo_4.0-1_amd64.deb &&
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/$ML_REPO_PKG &&
    sudo dpkg -i $ML_REPO_PKG

When running this command from https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md I got 404 error. It seems that link is broken.

**Comment by lukeyeager** [comment] 2015-12-03 17:11
Duplicate of #427.

**Closed by lukeyeager** 2015-12-03 17:11 UTC
Labels: duplicate
