### ISSUE TITLE
how to resume digits when abort the task last time

### ISSUE THREAD

**Issue by David-Jin** [NVIDIA/DIGITS#959] opened 2016-08-07 14:13 UTC
how to resume digits when abort the task last time

**Comment by gheinrich** [comment] 2016-08-08 08:37
There is no way to automatically restart from where an aborted job. What you can do however is to clone the aborted job and then in the `Previous Networks` tab, select the last snapshot of the aborted job. This will allow you to resume training from the weights of the last snapshot. Note however that this does not preserve the solver state, i.e. learning rate, momentum, etc. will be reset.

**Comment by lukeyeager** [comment] 2016-08-08 16:52
Duplicate of https://github.com/NVIDIA/DIGITS/issues/24.

**Closed** 2016-08-08 16:52 UTC
Labels: duplicate, question
