### ISSUE TITLE
torch_train.py sets CUDA_VISIBLE_DEVICES without checking if already set

### ISSUE THREAD

**Issue by QuesarVII** [NVIDIA/DIGITS#948] opened 2016-08-02 16:40 UTC
When DIGITS starts a torch job it uses the CUDA_VISIBLE_DEVICES environment variable to control which GPUs torch has access to.

If you start DIGITS with CUDA_VISIBLE_DEVICES already set to prevent a low end card from being included, that card can then be included anyway when torch_train.py resets the CUDA_VISIBLE_DEVICES environment variable.

I've patched the file to take into account the current value of the variable and then use the GPUs listed there to create a new setting for launching torch.

**Comment by QuesarVII** [comment] 2016-08-02 16:42
Here is the patch I created-
`
[digits-handle-cuda-visible-devices-already-set-for-torch-launch-patch.txt](https://github.com/NVIDIA/DIGITS/files/397571/digits-handle-cuda-visible-devices-already-set-for-torch-launch-patch.txt)

`

**Comment by lukeyeager** [comment] 2016-08-02 16:59
This is expected behavior. Use the DIGITS config to select GPUs instead of setting CUDA_VISIBLE_DEVICES.

https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/BuildDigits.md#troubleshooting

**Comment by QuesarVII** [comment] 2016-08-02 17:09
OK, I have set the GPUs with "python -m digits.config.edit --verbose" and this now works without the patch.

This issue indicated that CUDA_VISIBLE_DEVICES was OK to use to control GPUs available for digits:
https://github.com/NVIDIA/DIGITS/issues/647

Thanks

**Comment by lukeyeager** [comment] 2016-08-02 17:13
Oops you're right! I updated that comment, sorry.

**Comment by gheinrich** [comment] 2016-08-05 11:39
Closing since this is not an issue.

**Closed by gheinrich** 2016-08-05 11:39 UTC
