### ISSUE TITLE
running on multiple GPU is very slow

### ISSUE THREAD

**Issue by 201power** [NVIDIA/DIGITS#572] opened 2016-02-09 18:32 UTC
I am trying to run 50-layer residual network with 4 K40m GPUs and it's very slow (same batch_size 16 as running on single GPU), take 6 hours for 1 epoch. However, If I run it on 1 GPU the speed is normal. 

System: CentOS, digits v3, nvcaffe-0.14

BTW, I tried use Googlenet and it was ok on 4 GPUs. 

Any suggestion or potential issue?

**Comment by lukeyeager** [comment] 2016-02-09 18:44
Hi @201power, there are several things that could be going on:

1. cuDNN v4 is significantly faster than v3. That makes scaling across multiple GPUs less effective because a single GPU is just a lot quicker than it used to be and the GPU communication becomes more of a bottleneck. When [NCCL](https://github.com/NVIDIA/nccl) gets integrated into Caffe, that should help some to speed up the cross-GPU communication.

2. Some networks may be more conducive to multi-GPU than others. It's possible that the architecture of your ResNet requires more communication and less computation than other networks like GoogLeNet.

3. Or this could be a bug. **How much of a slowdown are we talking about?** If you use one GPU how long does it take for 1 epoch?

**Comment by 201power** [comment] 2016-02-09 19:07
Tried cuDNN v3, still the same speed, 1 epoch on 1 GPU take 4 mins, on 4 GPU take 6 hours. 
I used the prototxt here:
https://github.com/201power/ResNet-Generator-for-caffe/blob/master/resnet50_trainval.prototxt

**Comment by lukeyeager** [comment] 2016-02-09 19:21
When I try to run that network I get an error about `Message type "caffe.LayerParameter" has no field named "scale_param".`

[NVcaffe 0.14](https://github.com/NVIDIA/caffe/blob/v0.14.2/src/caffe/proto/caffe.proto#L465-L483) has the `batch_norm` layer type, but I guess you wrote this `scale` layer yourself?

**Comment by lukeyeager** [comment] 2016-02-09 19:29
Looks like you're getting the scale layer from https://github.com/BVLC/caffe/pull/3591, right?

I'm assuming you hacked up DIGITS to allow BVLC/caffe? This is definitely not a supported configuration. Still happy to help if I can, though!

**Comment by 201power** [comment] 2016-02-09 19:31
Yes, I merged NVcaffe 0.14 with caffe master branch, which has the scale layer:
https://github.com/201power/caffe

I think it's the issue with my caffe. I'll debug. Thanks!

BTW do nvcaffe plan to integrate scale layer?

**Comment by lukeyeager** [comment] 2016-02-09 19:41
> I think it's the issue with my caffe. I'll debug. Thanks!

Let me know when you resolve this issue - I hope it will be a simple configuration problem, but I'd like to know for sure that it's not a cuDNN or multi-GPU bug.

> BTW do nvcaffe plan to integrate scale layer?

NVcaffe will pick up the new scale layer (among other things) when we start working on our next release (see comment on release methodology [here](https://github.com/NVIDIA/caffe/issues/74#issuecomment-182024268)). We don't really pull in new features in-between releases - just major bugfixes.

**Comment by 201power** [comment] 2016-02-09 21:56
Thanks. Now I am using original caffe-0.14 with googlenet, however, it because very slow as well. 
Also, I am experiencing soft lockup everytime I tried to abort a job in digits, do you get the same msg as well?

![image](https://cloud.githubusercontent.com/assets/7299296/12931904/e4c18c6e-cf34-11e5-9dd2-61c8c8d4b858.png)

**Comment by lukeyeager** [comment] 2016-02-09 22:16
Hmm, that looks like trouble. How recent is your NVIDIA driver?

What happens when you try 2 GPUs instead of 1 or 4?

**Comment by 201power** [comment] 2016-02-09 22:30
I tried 2 GPU and it's also very slow. The nvidia driver is 352.79
1 GPU always works fine. 

Any other thing I can try/check?

**Comment by lukeyeager** [comment] 2016-02-09 22:38
I can go ask some people who would knowm more about this. A few questions before I do:

1. You're using [NVIDIA/caffe@caffe-0.14](https://github.com/NVIDIA/caffe/tree/caffe-0.14), right?
2. You're using cuDNN v4 (4.0.4), right?
3. Do you see the `soft lockup` error every time? Or does it only show up intermittently?

Can you try building without cuDNN at all and see if that makes a difference? I'm just spitballing here.

**Comment by 201power** [comment] 2016-02-09 23:14
1. Yes.
2. Yes. 
3. Yes, every time I abort a multi-GPU job I saw a soft lockup (not for single GPU job). 

I tried building caffe without cuDNN and it has the same issue, still very slow. 
Thanks.

**Comment by thatguymike** [comment] 2016-02-10 00:05
In the multigpu path there is sychronization between the GPUs that can cause delays, but I haven't seen those messages before.  Do you have enough disk IO to feed all the GPUs?  e.g. do you see messages about waiting for data in the log output?

**Comment by 201power** [comment] 2016-02-10 00:13
I do see one waiting for data in caffe log, during loading the network. However, it seems does not cause delays. 
![image](https://cloud.githubusercontent.com/assets/7299296/12935032/c01df952-cf47-11e5-8776-68d427e9a4bf.png)

I have 377G available disk space for the user, it should be fine.

**Comment by thatguymike** [comment] 2016-02-10 00:19
Not a question of diskspace, but IO throughput.  As you add GPUs, the pressure on disk goes up.  However, I haven't seen soft lockup errors before.  What motherboard chipset is this, e.g. Intel X99

**Comment by thatguymike** [comment] 2016-02-10 00:29
What version of Linux and kernel revision?  Anything in system logs from NVRM?

**Comment by 201power** [comment] 2016-02-10 00:31
The motherboard chipset is supermicro x10drg-0t

**Comment by thatguymike** [comment] 2016-02-10 00:36
K40s?

**Comment by 201power** [comment] 2016-02-10 00:36
I checked /var/log/messages and here are (part of) things I found related to NVRM:

![image](https://cloud.githubusercontent.com/assets/7299296/12935541/42ae81fe-cf4b-11e5-9521-bd8b9efc1108.png)

**Comment by lukeyeager** [comment] 2016-02-10 01:03
Can you try rolling back to your previously installed driver?

**Comment by 201power** [comment] 2016-02-10 01:26
It's a fresh computer, so it's the only version of driver we installed. 
We can try to use previous version of driver though.

**Comment by lukeyeager** [comment] 2016-02-10 01:29
Don't worry about it then. So this was working for you earlier this week and you didn't uninstall or reinstall a driver or anything like that?

I'm working on trying to reproduce this bug from my end, but it may take me a while to get Caffe built on CentOS since I haven't done that before...

**Comment by 201power** [comment] 2016-02-10 01:33
Yup, there is no change on the software/hardware since the last working job. 
Yes, install caffe on centos is a little time consuming, make sure you use OpenBLAS.

**Comment by lukeyeager** [comment] 2016-02-10 01:39
And when you go back to your original build, GoogLeNet still works?

**Comment by lukeyeager** [comment] 2016-02-10 01:58
Quick smoketest on Ubuntu passed. The scaling is bad but I'm not seeing any NVRM lines in `dmesg`.

OS: Ubuntu 14.04
GPUs: 2 x K40c
Driver: 352.79
Caffe: NVcaffe v0.14.2
cuDNN: 4.0.7

1 GPU: 1min 53sec
2 GPU: 2min 29sec

Time to try it on CentOS...

**Comment by 201power** [comment] 2016-02-10 03:56
The googlenet does not work anymore when I go back to the original build.

**Comment by lukeyeager** [comment] 2016-02-10 17:32
Smoketest on CentOS also passed.

OS: CentOS 7
GPUs: 2 x K40c
Driver: 352.79
Caffe: NVcaffe v0.14.2

1 GPU: 1min, 4sec
2 GPU: 50sec

(It's faster because I chose a different dataset and it's processing fewer images)

**Comment by 201power** [comment] 2016-02-10 17:42
Is it possible that supermicro chipset causing the issue?

**Comment by lukeyeager** [comment] 2016-02-10 17:46
Let's investigate whether you might have a bad GPU. Can you try this:

1. Do single-GPU training on each of your 4 GPUs
2. Do double-GPU training for each pair between your 4 GPUs (6 combinations total)

**Comment by lukeyeager** [comment] 2016-02-10 17:47
> Is it possible that supermicro chipset causing the issue?

Sure, that's possible too.

**Comment by 201power** [comment] 2016-02-10 18:11
I actually have 8xK40m, training on single GPU is fine:

![image](https://cloud.githubusercontent.com/assets/7299296/12956253/e9c33b34-cfdb-11e5-8001-55a66b6b507b.png)

However, training on two GPUs become very slow for all GPUs.

**Comment by lukeyeager** [comment] 2016-02-10 18:19
And you say that multi-GPU was running at a reasonable speed just a few days ago? Can you think of anything relevant that you might have changed on the machine since then?

**Comment by lukeyeager** [comment] 2016-02-10 18:30
FYI, this Dockerfile is enough to get Caffe built on CentOS7 (I had to do a bunch more hackery to build pycaffe and DIGITS, though).

https://gist.github.com/lukeyeager/fc0b21a62fca7b3edb24

**Comment by 201power** [comment] 2016-02-10 18:58
Nothing changed I can think of...just a reboot..
When I first installed caffe, it's running slow on multiple GPU. There is only 1 time I got it's running fast on 4 GPUs. 

Thanks for the docker file.

**Comment by lukeyeager** [comment] 2016-02-10 19:38
Let's take this offline for now. I sent you an email.

**Comment by 201power** [comment] 2016-02-10 21:06
I did not receive the email, did you sent to lihe.now@gmail.com?

**Comment by lukeyeager** [comment] 2016-02-11 01:05
In the end, this was a duplicate of https://github.com/NVIDIA/caffe/issues/10.

**Closed by lukeyeager** 2016-02-11 01:05 UTC
Labels: duplicate

**Comment by TimZaman** [comment] 2016-04-28 10:02
@lukeyeager Does the fact that we have to use an nvidia fork of Caffe mean that we cannot use vanilla ResNets with Caffe? Anyone got experience with that? (Resnet work fine with the latest torch from source)
