### ISSUE TITLE
Classifying many images is not working the same as one at a time

### ISSUE THREAD

**Issue by nemesisity** [NVIDIA/DIGITS#349] opened 2015-10-07 19:53 UTC
We are seeing different results when trying to classify many images listed in a file as opposed to doing each one individually.  Doing them one at a time gets very accurate results, but when supplying a list of those same test images, many are classified wrong.  The model is only looking for 2 cases.  Either it is a target item or not one.

**Comment by nemesisity** [comment] 2015-10-07 20:49
Closed by #261.  Nevermind.

**Comment by lukeyeager** [comment] 2015-10-07 20:56
Yep, duplicate of #255.

**Comment by nemesisity** [comment] 2015-10-08 16:40
So I just pulled the latest version and ran that side by side with the older 2.0 version on our DIGITS-devbox.  The results were the same.  I'm still seeing cars in the list that are classified as not-being cars, yet when I test that individual image against the model, it comes up as a car with 99+% accuracy.  This makes it very hard to verify results when we are questioning the validity of the classify multiple images results.

**Comment by lukeyeager** [comment] 2015-10-13 21:25
@nemesisity I forgot that we only partially fixed #255 in #261.

Can you verify that #361 fixes your issue?

**Closed** 2015-10-13 21:58 UTC
Labels: bug, caffe, duplicate

**Comment by nemesisity** [comment] 2015-10-14 15:04
I will give this a try later today to see if this works.
