### ISSUE TITLE
Forcing DIGITS to Always use GPU during TRAINING and TESTING?

### ISSUE THREAD

**Issue by michael-george-hart** [NVIDIA/DIGITS#76] opened 2015-04-16 14:26 UTC
@lukeyeager 
As Luke @lukeyeager  mentioned in one of the issues he/DIGITS is still working out away to cleanly allow GPU usage during testing phase of a DIGITS run. Currently GPU  usage only occurs during TRAINING; TESTING is entirely CPU....
A big is having TRAINING session on the order 6 to 10 hours on a mult-GPU cluster. Then find that TESTING turnaround time for those NN's are on the order of three plus hours . 

It would be very advantageous to all if we could force the code to use GPU during TESTING....

I can see exactly where the code applies data to the trained network .... I would like to know HOW to forcibly turn on GPU for that aspect of TESTING my NN's

Thanks
PS. @lukeyeager I know this is not a clean solution in general, but I think it is something most people would like to know how to do even it is not a part of a clean DIGITS's solution

**Comment by lukeyeager** [comment] 2015-04-16 17:03
Isn't this just a duplicate of #66?

**Comment by michael-george-hart** [comment] 2015-04-16 19:34
In many way it is with the exception I am asking if anyone know of a way so "I" can directly call some API in DIGITS/CAFFE just before the code actually start doing "TESTING" to force the testing to the GPU.... I alway know that I have a GPU ready version of Caffe with cuDNN installed. 

If you feel it is exactly question feel free to remove it  or merge it with #66

**Comment by lukeyeager** [comment] 2015-04-16 20:11
>I am asking if anyone know of a way so "I" can directly call some API in DIGITS/CAFFE just before the code actually start doing "TESTING" to force the testing to the GPU

As I said here: https://github.com/NVIDIA/DIGITS/issues/66#issuecomment-92467926, you can just uncomment one line and you'll be using the GPU for testing.

I'll close this issue and keep the other one open.

**Closed by lukeyeager** 2015-04-16 20:11 UTC

**Comment by michael-george-hart** [comment] 2015-04-16 20:34
I guess I didn't understand your answer.
Even now I am a bit confused

"uncomment one line"

What line where is that line?


On Thu, Apr 16, 2015 at 4:12 PM, Luke Yeager <notifications@github.com>
wrote:

> I am asking if anyone know of a way so "I" can directly call some API in
> DIGITS/CAFFE just before the code actually start doing "TESTING" to force
> the testing to the GPU
>
> As I said here: #66 (comment)
> <https://github.com/NVIDIA/DIGITS/issues/66#issuecomment-92467926>, you
> can just uncomment one line and you'll be using the GPU for testing.
>
> I'll close this issue and keep the other one open.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NVIDIA/DIGITS/issues/76#issuecomment-93829004>.
>



-- 
*"...Hope is what makes us strong. It is why we are here. It is what we
fight with when all is lost..."*

**Comment by lukeyeager** [comment] 2015-04-16 21:22
Oh sorry, I thought that was clear. Can you not see the link?

https://github.com/NVIDIA/DIGITS/blob/27386ed3326157de091f44468c2afcef7097fb8c/digits/model/tasks/caffe_train.py#L884-L885

**Comment by michael-george-hart** [comment] 2015-04-16 21:29
Yes...
Many thanks

On Thu, Apr 16, 2015 at 5:23 PM, Luke Yeager <notifications@github.com>
wrote:

> Oh sorry, I thought that was clear. Can you not see the link?
>
>
> https://github.com/NVIDIA/DIGITS/blob/27386ed3326157de091f44468c2afcef7097fb8c/digits/model/tasks/caffe_train.py#L884-L885
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NVIDIA/DIGITS/issues/76#issuecomment-93842683>.
>



-- 
*"...Hope is what makes us strong. It is why we are here. It is what we
fight with when all is lost..."*

**Comment by michael-george-hart** [comment] 2015-04-16 21:35
I just realize something....
As quick solution is look for some type of environment variable; like
"CAFFE_USE_GPU=1";
where, at least for LINUX, the user of the system can simply enable disable
the GPU usage
by
export CAFFE_USE_GPU = 1
to enable
of
export CAFFE_USE_GPU= <any other number/thing>
to force exclusively CPU usage.

You are already setting a number of environmental variables before one can
use DIGITS/CAFFE

What do you think?

On Thu, Apr 16, 2015 at 5:23 PM, Luke Yeager <notifications@github.com>
wrote:

> Oh sorry, I thought that was clear. Can you not see the link?
>
>
> https://github.com/NVIDIA/DIGITS/blob/27386ed3326157de091f44468c2afcef7097fb8c/digits/model/tasks/caffe_train.py#L884-L885
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NVIDIA/DIGITS/issues/76#issuecomment-93842683>.
>



-- 
*"...Hope is what makes us strong. It is why we are here. It is what we
fight with when all is lost..."*
