### ISSUE TITLE
Support for GoogLeNet

### ISSUE THREAD

**Issue by jmozah** [NVIDIA/DIGITS#11] opened 2015-03-20 10:47 UTC
> GoogLeNet: bvlc_googlenet's train_val.prototxt says "Cannot specify more than one Accuracy Layer"

Hi

Tried to create a custom model and pasted the bvlc_googlenet's tain_val.prototxt... The initialization of the model failed saying the above error... Looks like a bug for me...

**Comment by lukeyeager** [comment] 2015-03-20 16:38
This is not a bug, it's expected behavior. But I'll admit it's a little annoying. If you click on the helptip next to "Custom Network" on the "Custom Network" tab, you'll see some more information about the current limitations in DIGITS. GoogLeNet does some really cool tricks in their network (See [this paper](http://arxiv.org/abs/1409.4842)

**Comment by lukeyeager** [comment] 2015-03-20 16:46
This is not a bug, it's expected behavior. But I'll admit it's pretty annoying. If you click on the helptip next to "Custom Network" on the "Custom Network" tab, you'll see some more information about the current limitations on creating custom networks DIGITS.

GoogLeNet does some really cool tricks in their network (See [this paper](http://arxiv.org/abs/1409.4842), page 7 for a visualization of the network structure). The problem is that the training network (train_val.prototxt) and the deploy network (deploy.prototxt) are drastically different.

Having two textareas for submitting a train_val network and a deploy network is cumbersome. In anticipation of [this change](https://github.com/BVLC/caffe/issues/1245) going into caffe, I just put one textarea in DIGITS and do some [ugly, tedious stuff](https://github.com/NVIDIA/DIGITS/blob/v1.0/digits/model/tasks/caffe_train.py#L104-L355) in the backend to split that one network into the two networks required by caffe.

Once that "All-in-one nets" feature comes out, you'll be able to use GoogLeNet and other interesting architectures, but for now you have to stick with the format used by LeNet, AlexNet and VGG (and many others).

**Comment by lukeyeager** [comment] 2015-03-23 16:48
Closing this bug as it is an intentional limitation for now.

**Comment by ypyean** [comment] 2015-03-28 04:56
@lukeyeager  Is there a simple way to import GoogLeNet net definition to DIGITS for model training now? Since we don't have idea when the "All-in-one nets" will be ready.

**Comment by lukeyeager** [comment] 2015-03-30 19:41
I'm reopening [and renaming] this issue since it's coming up a lot.

**Closed** 2015-04-07 01:10 UTC
Labels: enhancement
