### ISSUE TITLE
[proposed question/bug] Can not download model in DIGITS on Windows

### ISSUE THREAD

**Issue by JieZou1** [NVIDIA/DIGITS#919] opened 2016-07-20 18:20 UTC
As title says,

When using Chrome, it reports:

IOError
[Errno 13] Permission denied: 'c:\\users\\jzou\\appdata\\local\\temp\\1\\tmpevv0_b'

When using IE, it simply shows "HTTP 500 Internal Server Error" page.

Any ideas? Thanks.

The DIGITS info is copied below:

DIGITS version: 
 4.1-dev
Caffe version: 
 1.0.0-rc3
Caffe flavor: 
 BVLC

**Comment by lukeyeager** [comment] 2016-07-20 19:08
@IsaacYangSLA can you look into it? It's probably caused by https://github.com/NVIDIA/DIGITS/pull/891.

**Comment by IsaacYangSLA** [comment] 2016-07-21 16:14
@lukeyeager , sure.

**Comment by IsaacYangSLA** [comment] 2016-07-21 19:00
@Lucaszw , if you have time, can you try it in Linux?  I think the fix is platform independent, and I hope this fix doesn't break your codes.

**Comment by IsaacYangSLA** [comment] 2016-07-21 19:06
@JieZou1 , thanks for spotting this issue for us.  Can you help check if this issue can be solved in this pull request?  The easiest way to try it is to replace that file directly and restart your DIGITS.  After downloading the model, check if info.json inside that tar.gz file is not corrupted.  Thanks.

**Comment by JieZou1** [comment] 2016-07-21 20:58
After replacing views.py, the button seems working Okay now. Many thanks.

**Comment by IsaacYangSLA** [comment] 2016-07-21 21:23
@JieZou1 , thanks for testing it.  We will close this after merging the PR.  If you encounter the same issue again, please leave a comment here, even after it's closed, so we can track the fix.

**Comment by Lucaszw** [comment] 2016-07-22 00:55
@JieZou1 Thanks for spotting this! @IsaacYangSLA I will test this on Linux as well, and then merge.

**Closed** 2016-07-22 01:02 UTC
Labels: bug, platform
