### ISSUE TITLE
"Test One Image" does not handle non-square images correctly

### ISSUE THREAD

**Issue by ulmangt** [NVIDIA/DIGITS#100] opened 2015-05-07 16:15 UTC
When uploading a non-square grayscale dataset, image width and height appear to be flipped in various places.

For example: for 91 x 256 images the "See Example"  button on the "New Image Classification Dataset" screen shows a vertically oriented Mona Lisa (longer than she is wide). But the mean image reported when the dataset is finished processing is wider than it is long.

When a model is built using such a dataset, DIGITS can report excellent validation performance, but actually perform poorly when applying the model to test data.

See the following Google Groups discussion for additional details:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/digits-users/X3V1mzHt2AM/JpMo7Vz1SwYJ

**Comment by lukeyeager** [comment] 2015-05-07 16:41
Duplicate of #36, except that you're providing more detailed information - thanks!

This is fixed in [version 1.1](https://github.com/NVIDIA/DIGITS/releases/tag/v1.1.0) (but I forgot to list it as a bugfix).

**Closed by lukeyeager** 2015-05-07 16:41 UTC
