### ISSUE TITLE
Training ILSVRC2012 with Torch fails.

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#666] opened 2016-04-04 12:40 UTC
I am training ILSVRC2012 (1.2M images, 256x256) with Digits (AlexNet). Works great on caffe+digits. Amazing job there, well done! 

**Version: v3.2.0-61-g0ce28b9** (almost the latest)

But I actually am working with torch myself. Which does not seem to cooperate. I am using vanilla AlexNet. This is the output:

![image](https://cloud.githubusercontent.com/assets/7721540/14248105/0373ca5a-fa73-11e5-965d-87895f56eb05.png)

```

2016-04-04 14:30:02 [INFO ] Loading mean tensor from /home/tzaman/MOUNT/LARGEHD/digits/jobs/20160401-161438-510e/mean.jpg file
2016-04-04 14:30:02 [INFO ] Loading label definitions from /home/tzaman/MOUNT/LARGEHD/digits/jobs/20160401-161438-510e/labels.txt file
2016-04-04 14:30:02 [INFO ] found 998 categories
2016-04-04 14:30:02 [INFO ] creating data readers
2016-04-04 14:30:03 [INFO ] opening LMDB database: /home/tzaman/MOUNT/LARGEHD/digits/jobs/20160401-161438-510e/train_db
2016-04-04 14:30:03 [INFO ] opening LMDB database: /home/tzaman/MOUNT/LARGEHD/digits/jobs/20160401-161438-510e/train_db
2016-04-04 14:30:03 [INFO ] opening LMDB database: /home/tzaman/MOUNT/LARGEHD/digits/jobs/20160401-161438-510e/train_db
2016-04-04 14:30:03 [INFO ] opening LMDB database: /home/tzaman/MOUNT/LARGEHD/digits/jobs/20160401-161438-510e/train_db
2016-04-04 14:34:29 [FAIL] /usr/share/lua/5.1/threads/threads.lua:264:
[thread 2 callback] /home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:326: not enough memory
stack traceback:
[C]: in function '(for generator)'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:326: in function 'lmdb_getKeys'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:194: in function 'new'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:526: in function </home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:521>
[C]: in function 'xpcall'
/usr/share/lua/5.1/threads/threads.lua:231: in function 'callback'
/usr/share/lua/5.1/threads/queue.lua:65: in function </usr/share/lua/5.1/threads/queue.lua:41>
[C]: in function 'pcall'
/usr/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
[thread 1 callback] /home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:326: not enough memory
stack traceback:
[C]: in function '(for generator)'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:326: in function 'lmdb_getKeys'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:194: in function 'new'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:526: in function </home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:521>
[C]: in function 'xpcall'
/usr/share/lua/5.1/threads/threads.lua:231: in function 'callback'
/usr/share/lua/5.1/threads/queue.lua:65: in function </usr/share/lua/5.1/threads/queue.lua:41>
[C]: in function 'pcall'
/usr/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
[thread 4 callback] /home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:326: not enough memory
stack traceback:
[C]: in function '(for generator)'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:326: in function 'lmdb_getKeys'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:194: in function 'new'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:526: in function </home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:521>
[C]: in function 'xpcall'
/usr/share/lua/5.1/threads/threads.lua:231: in function 'callback'
/usr/share/lua/5.1/threads/queue.lua:65: in function </usr/share/lua/5.1/threads/queue.lua:41>
[C]: in function 'pcall'
/usr/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
[thread 3 callback] /home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:326: not enough memory
stack traceback:
[C]: in function '(for generator)'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:326: in function 'lmdb_getKeys'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:194: in function 'new'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:526: in function </home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:521>
[C]: in function 'xpcall'
/usr/share/lua/5.1/threads/threads.lua:231: in function 'callback'
/usr/share/lua/5.1/threads/queue.lua:65: in function </usr/share/lua/5.1/threads/queue.lua:41>
[C]: in function 'pcall'
/usr/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
DIGITS Lua Error
stack traceback:
[C]: in function 'error'
/usr/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
/usr/share/lua/5.1/threads/threads.lua:142: in function 'specific'
/usr/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/data.lua:519: in function 'new'
/home/tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/main.lua:220: in main chunk
[C]: in function 'dofile'
...tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/wrapper.lua:25: in function <...tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/wrapper.lua:25>
[C]: in function 'xpcall'
...tzaman/INSTALL/NVIDIA/DIGITS/tools/torch/wrapper.lua:25: in main chunk
[C]: in function 'dofile'
/usr/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00406670
```

**Comment by gheinrich** [comment] 2016-04-04 17:34
Thanks for the report Tim, I believe this is a duplicate of #659. We need a data loader that scales better to bigger datasets. I will be working on this but I am travelling this week so I won't be able to give this a lot of time. I am closing this issue for now, let's track this on #659.

**Closed** 2016-04-04 17:41 UTC
