### ISSUE TITLE
Ability to restart training from a aborted job

### ISSUE THREAD

**Issue by jmozah** [NVIDIA/DIGITS#162] opened 2015-07-09 07:23 UTC
If training gets aborted due to some reason (spot prices).. then it is currently not possible to
restart the training from the last snapshot using DIGITS. It would be a good feature to give an option to restart the training from a previous snapshot.

**Comment by lukeyeager** [comment] 2015-07-09 16:22
Duplicate of #24. Didn't you already comment on that one?

**Closed by lukeyeager** 2015-07-09 16:22 UTC
