### ISSUE TITLE
How to use torch to train one net?

### ISSUE THREAD

**Issue by JulyUp** [NVIDIA/DIGITS#974] opened 2016-08-15 09:28 UTC
I have installed torch in my ubuntu14.04. When I  create an image classification job using lenet convnet with torch framework, it shows error:

2016-08-15 11:03:44 [FAIL] ...earning-tools/torch/install/share/lua/5.1/trepl/init.lua:384: ...earning-tools/torch/install/share/lua/5.1/trepl/init.lua:384: module 'hdf5' not found:No LuaRocks module found for hdf5
no field package.preload['hdf5']
no file '/home/xxx/work/DIGITS-digits-4.0/tools/torch/hdf5.lua'
no file '/home/xxx/work/DIGITS-digits-4.0/tools/torch/hdf5.lua'
no file '/home/xxx/work/DIGITS-digits-4.0/tools/torch/hdf5.lua'
no file '/home/xxx/.luarocks/share/lua/5.1/hdf5.lua'
no file '/home/xxx/.luarocks/share/lua/5.1/hdf5/init.lua'
no file '/home/xxx/work/deeplearning-tools/torch/install/share/lua/5.1/hdf5.lua'
no file '/home/xxx/work/deeplearning-tools/torch/install/share/lua/5.1/hdf5/init.lua'
no file '/home/xxx/home/xxx/work/deeplearning-tools/torch/install/share/lua/5.1/hdf5.lua'
no file '/home/xxx/home/xxx/work/deeplearning-tools/torch/install/share/lua/5.1/hdf5/init.lua'
no file './hdf5.lua'
no file '/home/xxx/home/xxx/work/deeplearning-tools/torch/install/share/luajit-2.1.0-beta1/hdf5.lua'
no file '/usr/local/share/lua/5.1/hdf5.lua'
no file '/usr/local/share/lua/5.1/hdf5/init.lua'
no file '/home/xxx/.luarocks/lib/lua/5.1/hdf5.so'
no file '/home/xxx/work/deeplearning-tools/torch/install/lib/lua/5.1/hdf5.so'
no file '/home/xxx/work/deeplearning-tools/torch/install/lib/hdf5.so'
no file '/home/xxx/home/xxx/work/deeplearning-tools/torch/install/lib/hdf5.so'
no file '/home/xxx/home/xxx/work/deeplearning-tools/torch/install/lib/lua/5.1/hdf5.so'
no file './hdf5.so'
no file '/usr/local/lib/lua/5.1/hdf5.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
DIGITS Lua Error
stack traceback:
[C]: in function 'error'
...earning-tools/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
/home/xxx/work/DIGITS-digits-4.0/tools/torch/main.lua:174: in main chunk
[C]: in function 'dofile'
.../xxx/work/DIGITS-digits-4.0/tools/torch/wrapper.lua:25: in function <.../xxx/work/DIGITS-digits-4.0/tools/torch/wrapper.lua:25>
[C]: in function 'xpcall'
.../xxx/work/DIGITS-digits-4.0/tools/torch/wrapper.lua:25: in main chunk
[C]: in function 'dofile'
...ools/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00406670

What should I sovle this error?

**Comment by lukeyeager** [comment] 2016-08-15 16:32
> No LuaRocks module found for hdf5

That looks pretty clear to me. Did you follow these instructions?

https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/BuildTorch.md#extra-dependencies

**Comment by JulyUp** [comment] 2016-08-16 02:46
@lukeyeager Thank you very much. I did those instructions as you said above, but another error showed:

"2016-08-16 10:11:55 [INFO ] Loading mean tensor from /home/xxx/work/digits/digits/jobs/20160816-101152-d286/mean.jpg file
2016-08-16 10:11:55 [INFO ] Loading label definitions from /home/xxx/work/digits/digits/jobs/20160815-200425-053a/labels.txt file
2016-08-16 10:11:55 [INFO ] found 10 categories
2016-08-16 10:11:55 [INFO ] creating data readers
2016-08-16 10:11:55 [FAIL] ...ng-tools/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] /home/xxx/work/digits/tools/torch/utils.lua:203: error loading module 'lightningmdb' from file '/home/xxx/work/deeplearning-tools/torch/install/lib/lua/5.1/lightningmdb.so':
/home/xxx/work/deeplearning-tools/torch/install/lib/lua/5.1/lightningmdb.so: undefined symbol: mdb_txn_id"


But I have installed lightningmdb with the instruction "luarocks install lightningmdb LMDB_INCDIR=/usr/include LMDB_LIBDIR=/usr/lib/x86_64-linux-gnu". Now how to sovle this error?

**Comment by JulyUp** [comment] 2016-08-16 02:54
@lukeyeager  When doing the command ./digits-devserver, the tip is as follow: 
"==================================== Torch =====================================
Where is torch installed?

	Suggested values:
	(*)  [Previous]       /home/xxx/work/deeplearning-tools/torch/install
	(P)  [PATH/TORCHPATH] <PATHS>
	(N)  [none]           <NONE>
"


I input the path "/home/xxx/work/deeplearning-tools/torch/install".  Is this corret?

**Comment by JulyUp** [comment] 2016-08-16 06:59
@lukeyeager  I have sovled this problem. 
I read #908, in which @gheinrich suggested the command "luarocks install lightningmdb 0.9.18.1-1 LMDB_INCDIR=/usr/include LMDB_LIBDIR=/usr/lib/x86_64-linux-gnu" rather than the command "luarocks install lightningmdb LMDB_INCDIR=/usr/include LMDB_LIBDIR=/usr/lib/x86_64-linux-gnu" in [https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/BuildTorch.md#extra-dependencies ](url) above you said.  I am still confused. But I am very happy  when running convnet with torch. 
Thank your contribution very much!

**Comment by lukeyeager** [comment] 2016-08-16 17:30
Oops looks like we didn't add #928 into the `digits-4.0` branch, which is why that documentation is wrong. #981 fixes this. Thanks for pointing it out!

**Comment by JulyUp** [comment] 2016-08-17 01:42
That's all right.  But I suggest digits can support some faster frameworks such as mxnet and cntk. Caffe and torch is a little bit slow.

**Comment by JulyUp** [comment] 2016-08-17 01:42
@lukeyeager  That's all right. But I suggest digits can support some faster frameworks such as mxnet and cntk. Caffe and torch is a little bit slow.

**Comment by lukeyeager** [comment] 2016-08-17 16:11
That request is a duplicate of #967. Feel free to upvote it.

**Closed by lukeyeager** 2016-08-17 16:11 UTC
Labels: question, torch
