### ISSUE TITLE
Inference and Edge browser

### ISSUE THREAD

**Issue by pansk** [NVIDIA/DIGITS#783] opened 2016-05-25 12:54 UTC
Inference from a remote Win10 machine using Edge browser is not working, producing an error: "
HTTP 400 error
It’s not you, it’s this link (it appears to be broken)
Try this
•Retype the URL
•Go back to the last page
•Search for the page"

From the same PC, using FireFox, Chrome and even Internet Explorer, do the job.

**Comment by lukeyeager** [comment] 2016-05-25 18:38
Sorry, you're saying you get a 400 error when trying to run inference on a model when using Win10's Edge browser? I don't have access to a Win10 machine to test on. @IsaacYangSLA - you're not running Win10 are you?

@pansk what's all this mean?
> It’s not you, it’s this link (it appears to be broken)
Try this
•Retype the URL
•Go back to the last page
•Search for the page"

**Comment by pansk** [comment] 2016-05-25 20:07
The quoted text is exactly what Edge reports (screenshot follows):

![image](https://cloud.githubusercontent.com/assets/1263535/15554503/e18d9996-22c4-11e6-83d6-01c20183df67.png)

**Comment by lukeyeager** [comment] 2016-05-25 20:13
Haha oh I see

**Comment by IsaacYangSLA** [comment] 2016-05-25 21:08
Let me try to reproduce the issue.

**Comment by IsaacYangSLA** [comment] 2016-05-27 03:37
I did Classify One and Classify Many on Edge/Windows 10 64bit, but I couldn't duplicate this issue.
![image](https://cloud.githubusercontent.com/assets/5758988/15597085/a3429606-2381-11e6-8651-b27f6bc88baa.png)

**Comment by IsaacYangSLA** [comment] 2016-05-27 16:11
The above issue can be resolved by refreshing the browser cache.  @pansk, can you help verify if this issue is caused by similar reason?  Thanks.

**Comment by pansk** [comment] 2016-05-30 09:56
Sorry, I remember commenting on this one after fixing the other issue, but I cannot find my comment.
No, clearing the cache didn't solve the problem. I also tried cleaning all the cookies, and didn't help either.
I tested the "one" with both URL and local image, and the test many with URL. Always the same problem.

This issue is actually older than the other one (I thought it was my installation problem, and maybe it is, but finding a similar issue I decided to submit this one too).

Today I'll ask a colleague to verify on a different PC.

**Comment by IsaacYangSLA** [comment] 2016-06-03 15:17
@pansk , thanks for the clarification.  I tried this version, but didn't see the issue.
![image](https://cloud.githubusercontent.com/assets/5758988/15783520/53e61c9e-2963-11e6-983a-57f93f0324e7.png)
I received your email, and will reply over that channel to see if we can work together to figure it out.

**Closed** 2016-10-31 17:31 UTC
Labels: windows
