### ISSUE TITLE
Batch size: Not a valid integer value. Number None must be at least 1.

### ISSUE THREAD

**Issue by enoonIT** [NVIDIA/DIGITS#718] opened 2016-04-29 07:45 UTC
After most recent commit I always get the following error when creating a new Classification Model:
![2016-04-29 09_42_36-new image classification model](https://cloud.githubusercontent.com/assets/7884236/14910566/d852224c-0dee-11e6-83d8-3ec746a743c2.png)

And the network parameters are (automatically) set as:
![2016-04-29 09_42_58-new image classification model](https://cloud.githubusercontent.com/assets/7884236/14910563/d655e67c-0dee-11e6-976b-04e55744fb96.png)

**Comment by enoonIT** [comment] 2016-04-29 08:09
Reverting to 7f484b9bfc0181161790368dbd4ab13e31fefd7d fixes this

**Comment by lukeyeager** [comment] 2016-04-29 20:06
Duplicate of https://github.com/NVIDIA/DIGITS/issues/717.

**Closed by lukeyeager** 2016-04-29 20:06 UTC
