### ISSUE TITLE
can't start digits server under windows

### ISSUE THREAD

**Issue by korabelnikov** [NVIDIA/DIGITS#1157] opened 2016-10-12 08:27 UTC
I folowed instruction for windows, but I use Anaconda as python.

```
D:\smedx\DIGITS>python digits-devserver
  File "digits-devserver", line 6
    python -m digits $@
                   ^
SyntaxError: invalid syntax
```

**Comment by lukeyeager** [comment] 2016-10-12 16:21
Duplicate of https://github.com/NVIDIA/DIGITS/issues/1149

**Closed by lukeyeager** 2016-10-12 16:21 UTC
