### ISSUE TITLE
When I create model follow the code step,following errors occured . If you have this problem,thank you!

### ISSUE THREAD

**Issue by hangongzi** [NVIDIA/DIGITS#1302] opened 2016-11-28 14:11 UTC
ERROR: Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Python (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, Concat, ContrastiveLoss, Convolution, Crop, Data, Deconvolution, DetectNetTransformation, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, Input, L1Loss, LRN, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Pooling, Power, ReLU, Reduction, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, Tile, WindowData)

**Comment by gheinrich** [comment] 2016-11-28 15:15
Please search the archives before filing issues. Closing as duplicate of #1253

**Closed by gheinrich** 2016-11-28 15:15 UTC
