### ISSUE TITLE
ImportError: No module named sgunicorn

### ISSUE THREAD

**Issue by SevenGong** [NVIDIA/DIGITS#958] opened 2016-08-05 11:03 UTC
When I do "./digits-derver"，I got the error:
Error: class uri 'socketio.sgunicorn.GeventSocketIOWorker' invalid or not found: 

[Traceback (most recent call last):
  File "/home/XXX/anaconda2/lib/python2.7/site-packages/gunicorn/util.py", line 142, in load_class
    mod = import_module('.'.join(components))
  File "/home/XXX/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named sgunicorn

 But I have installed the gunicorn.    What should I do?  Need your help.

**Comment by rjgowth11** [comment] 2016-08-05 11:15
Hi,
please walkthrough this linked they have already solve this issuse:
https://groups.google.com/forum/#!topic/digits-users/_6xGrd_FmHA
RJG

**Comment by gheinrich** [comment] 2016-08-05 11:31
@SevenGong I don't recommend using Anaconda. Our install instructions are for the standard Python distribution.

**Comment by SevenGong** [comment] 2016-08-05 11:41
@gheinrich  Thank you.  I know Anaconda  is very popular now, so I use it. 
Is the problem really coursed by the anaconda?  Let me try.

**Comment by SevenGong** [comment] 2016-08-05 11:44
@rjgowth11  sorry. I can open the URL. Can you tell me how to sovle it ? Thank you very much.

**Comment by gheinrich** [comment] 2016-08-05 11:56
> Is the problem really coursed by the anaconda?

Yes, `pip` installs packages into the standard Python distribution. If you use an Anaconda distribution, the commands from our install instructions won't work.

**Comment by rjgowth11** [comment] 2016-08-05 13:16
No module named sgunicorn?
10 posts by 4 authors
	Sam Bryfczynski 	
11/10/15
I'm trying to run ./digits-server

I just get an error: No module named sgunicorn

I've used pip to install all the requirements (I think). Anyone else have this problem or any advise?

Thanks!
Best answer
	Luke Yeager 	
11/12/15
Ok this is definitely caused by one (or more) library upgrading their requirements lists. I'm seeing problems with both digits-server and digits-devserver.

Can you try this requirements list? I made a few of the requirements more specific.

https://github.com/lukeyeager/DIGITS/commit/33cd1992e6f1f867b7352233fdef211a56098451
- show quoted text -
0
0
Marked best answer by(Asker)Sam Bryfczynski
See this answer in its original position
All replies
	Greg Heinrich 	
11/10/15
Hi Sam, do you see 'gunicorn', 'gevent' and 'Flask-SocketIO' in your `pip list`?
- show quoted text -
0
0
	Sam Bryfczynski 	
11/11/15
Yeah I do. ....maybe I install some other libraries that are conflicting? Sorry. New to python. Below is the full error and my pip list.

Error: class uri 'socketio.sgunicorn.GeventSocketIOWorker' invalid or not found: 

[Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 132, in load_class
    mod = __import__('.'.join(components))
ImportError: No module named socketio.sgunicorn
]


My Pip List:
adium-theme-ubuntu (0.3.4)
apt-xapian-index (0.45)
beautifulsoup4 (4.2.1)
blinker (1.3)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
cvxopt (1.1.4)
cycler (0.9.0)
Cython (0.20.1.post0)
debtagshw (0.1)
decorator (4.0.4)
defer (1.0.6)
dirspec (13.10)
duplicity (0.6.23)
Flask (0.10.1)
Flask-SocketIO (1.0)
Flask-WTF (0.12)
gevent (1.0.2)
gevent-websocket (0.9.5)
greenlet (0.4.9)
gunicorn (17.5)
gyp (0.1)
h5py (2.2.1)
html5lib (0.999)
httplib2 (0.8)
itsdangerous (0.24)
Jinja2 (2.8)
joblib (0.7.1)
leveldb (0.1)
lmdb (0.87)
lockfile (0.8)
lxml (3.3.3)
MarkupSafe (0.23)
matplotlib (1.5.0)
networkx (1.10)
nose (1.3.1)
numexpr (2.2.2)
numpy (1.10.1)
oauthlib (0.6.1)
oneconf (0.3.7.14.4.1)
openpyxl (1.7.0)
PAM (0.4.2)
pandas (0.13.1)
patsy (0.2.1)
pexpect (3.1)
Pillow (3.0.0)
pip (7.1.2)
piston-mini-client (0.7.5)
protobuf (2.6.1)
pycrypto (2.6.1)
pycups (1.9.66)
pydot2 (1.0.33)
pygobject (3.12.0)
pyinotify (0.9.4)
pyOpenSSL (0.13)
pyparsing (2.0.5)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu1)
python-dateutil (2.4.2)
python-debian (0.1.21-nmu2ubuntu2)
python-engineio (0.7.2)
python-gflags (1.5.1)
python-socketio (0.6.1)
pytz (2015.7)
pyxdg (0.25)
PyYAML (3.10)
reportlab (3.0)
requests (2.8.1)
scikit-image (0.11.3)
scipy (0.16.1)
sessioninstaller (0.0.0)
setuptools (3.3)
simplejson (3.3.1)
six (1.10.0)
software-center-aptd-plugins (0.0.0)
statsmodels (0.5.0)
system-service (0.1.6)
tables (3.1.1)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
unity-lens-photos (1.0)
urllib3 (1.7.1)
Werkzeug (0.11.1)
wheel (0.24.0)
WTForms (2.0.2)
xdiagnose (3.6.3build2)
xlrd (0.9.2)
xlwt (0.7.5)
zope.interface (4.0.5)
- show quoted text -
0
0
	Luke Yeager 	
11/12/15
Ok this is definitely caused by one (or more) library upgrading their requirements lists. I'm seeing problems with both digits-server and digits-devserver.

Can you try this requirements list? I made a few of the requirements more specific.

https://github.com/lukeyeager/DIGITS/commit/33cd1992e6f1f867b7352233fdef211a56098451
- show quoted text -
0
0
Marked best answer by(Asker)Sam Bryfczynski
	Sam Bryfczynski 	
11/12/15
Thanks! This worked great....well kind of. 

The server started up :) and I can go to the site. But jobs dont seem to be running.  I configure a job just like I do with ./runme, but it seems to just hang with no training ever happening. 

The console just says the following (which it also says in ./runme but continues anyways):
2015-11-12 07:28:41 [20151112-072840-ce31] [DEBUG] Train Caffe Model task started.
2015-11-12 07:28:41 [20151112-072840-ce31] [INFO ] Train Caffe Model task started.
2015-11-12 07:28:42 [20151112-072840-ce31] [ERROR] Train Caffe Model: Attempting to upgrade input file specified using deprecated V1LayerParameter: /home/sam/Documents/caffe/models/bvlc_googlenet/bvlc_googlenet.caffemodel
2015-11-12 07:28:42 [20151112-072840-ce31] [ERROR] Train Caffe Model: Attempting to upgrade input file specified using deprecated V1LayerParameter: /home/sam/Documents/caffe/models/bvlc_googlenet/bvlc_googlenet.caffemodel

Not sure if there are other log files around.
- show quoted text -
0
1
	Luke Yeager 	
11/13/15
Is it possible you're running into this issue?
https://github.com/BVLC/caffe/issues/3279#issuecomment-154860188

I'd prefer it if you created a new thread for this issue. It's helpful to have separate thread for separate issues for the sake of searching.
- show quoted text -
0
0
	Saverio De Vito 	
Feb 3

Hi,
I got a similar error on production error while  my devserver succeeds to initialize and actually responds on port 5000:


Error: class uri 'socketio.sgunicorn.GeventSocketIOWorker' invalid or not found:

[Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 132, in load_class

    mod = __import__('.'.join(components))
ImportError: No module named sgunicorn
]

Any advise about how to solve?
Thank you so much,
Saverio


my pip list is:
-ipap11helper (0.1)
async (0.6.1)
backports.ssl-match-hostname (3.4.0.2)
Beaker (1.5.4)
beautifulsoup4 (4.3.2)
blivet (0.61.15.37)
Bottleneck (0.7.0)
Brlapi (0.6.0)
cffi (0.8.6)
chardet (2.2.1)
configobj (4.7.2)
configshell-fb (1.1.18)
coverage (3.6b3)
cryptography (0.8.2)
cupshelpers (1.0)
Cython (0.23.4)
decorator (3.4.0)
di (0.3)
dnspython (1.12.0)
dockerfile-parse (0.0.5)
enum34 (1.0.4)
ethtool (0.8)
fedpkg (1.20)
firstboot (19.5)
Flask (0.10.1)
Flask-SocketIO (2.0)
Flask-WTF (0.12)
freeipa (2.0.0a0)
fros (1.0)
gevent (1.0.2)-ipap11helper (0.1)
async (0.6.1)
backports.ssl-match-hostname (3.4.0.2)
Beaker (1.5.4)
beautifulsoup4 (4.3.2)
blivet (0.61.15.37)
Bottleneck (0.7.0)
Brlapi (0.6.0)
cffi (0.8.6)
chardet (2.2.1)
configobj (4.7.2)
configshell-fb (1.1.18)
coverage (3.6b3)
cryptography (0.8.2)
cupshelpers (1.0)
Cython (0.23.4)
decorator (3.4.0)
di (0.3)
dnspython (1.12.0)
dockerfile-parse (0.0.5)
enum34 (1.0.4)
ethtool (0.8)
fedpkg (1.20)
firstboot (19.5)
Flask (0.10.1)
Flask-SocketIO (2.0)
Flask-WTF (0.12)
freeipa (2.0.0a0)
fros (1.0)
gevent (1.0.2)
gitdb (0.5.4)
GitPython (0.3.2rc1)
greenlet (0.4.9)
gunicorn (17.5)
h5py (2.3.1)
html5lib (0.999)
iniparse (0.4)
initial-setup (0.3.9.30)
ipaplatform (4.2.0)
ipapython (4.2.0)
IPy (0.75)
itsdangerous (0.24)
javapackages (1.0.0)
Jinja2 (2.8)
kerberos (1.1)
kitchen (1.1.1)
kmod (0.1)
langtable (0.0.31)
lmdb (0.88)
lockfile (0.9.1)
lxml (3.2.1)
M2Crypto (0.21.1)
Magic-file-extensions (0.2)
Mako (0.8.1)
MarkupSafe (0.23)
matplotlib (1.2.0)
munch (2.0.2)
netaddr (0.7.5)
networkx (1.11)
nose (1.3.0)
ntplib (0.3.2)
numexpr (2.3)
numpy (1.10.4)
osbs-client (0.15)
packagedb-cli (2.8.2)
pandas (0.17.0)
Paste (1.7.5.1)
pciutils (1.7.3)
perf (0.1)
pexpect (2.3)
Pillow (2.3.0)
pip (8.0.2)
ply (3.4)
policycoreutils-default-encoding (0.1)
protobuf (2.6.1)
pyasn1 (0.1.6)
pycparser (2.14)
pycups (1.9.63)
pycurl (7.19.0)
pydot2 (1.0.33)
pygobject (3.14.0)
pygpgme (0.3)
pyinotify (0.9.4)
pykickstart (1.99.66.6)
pyliblzma (0.5.3)
pyOpenSSL (0.13.1)
pyparsing (1.5.6)
pyparted (3.9)
pysmbc (1.0.13)
python-augeas (0.5.0)
python-bugzilla (1.2.2)
python-dateutil (1.5)
python-default-encoding (0.1)
python-dmidecode (3.10.13)
python-engineio (0.8.7)
python-fedora (0.6.4)
python-ldap (2.4.15)
python-meh (0.25.2)
python-nss (0.16.0)
python-socketio (1.0)
python-yubico (1.2.3)
pytz (2012d)
pyudev (0.15)
pyusb (1.0.0b1)
pyxattr (0.5.1)
pyxdg (0.25)
qrcode (5.0.1)
redhat-access-insights (1.0.6)
requests (2.6.0)
rhnlib (2.5.65)
rhsm (1.15.4)
rpkg (1.35)
rtslib-fb (2.1.57)
scikit-image (0.11.3)
scipy (0.17.0)
seobject (0.1)
sepolicy (1.1)
setroubleshoot (1.1)
setuptools (19.7)
simplejson (3.3.3)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
smmap (0.8.1)
SSSDConfig (1.13.0)
tables (3.2.0rc3)
targetcli-fb (2.1.fb41)
Tempita (0.5.1)
urlgrabber (3.10)
urllib3 (1.10.2)
urwid (1.1.1)
Werkzeug (0.11.3)
WTForms (2.1)
yum-langpacks (0.4.2)
yum-metadata-parser (1.1.4)
gitdb (0.5.4)
GitPython (0.3.2rc1)
greenlet (0.4.9)
gunicorn (17.5)
h5py (2.3.1)
html5lib (0.999)
iniparse (0.4)
initial-setup (0.3.9.30)
ipaplatform (4.2.0)
ipapython (4.2.0)
IPy (0.75)
itsdangerous (0.24)
javapackages (1.0.0)
Jinja2 (2.8)
kerberos (1.1)
kitchen (1.1.1)
kmod (0.1)
langtable (0.0.31)
lmdb (0.88)
lockfile (0.9.1)
lxml (3.2.1)
M2Crypto (0.21.1)
Magic-file-extensions (0.2)
Mako (0.8.1)
MarkupSafe (0.23)
matplotlib (1.2.0)
munch (2.0.2)
netaddr (0.7.5)
networkx (1.11)
nose (1.3.0)
ntplib (0.3.2)
numexpr (2.3)
numpy (1.10.4)
osbs-client (0.15)
packagedb-cli (2.8.2)
pandas (0.17.0)
Paste (1.7.5.1)
pciutils (1.7.3)
perf (0.1)
pexpect (2.3)
Pillow (2.3.0)
pip (8.0.2)
ply (3.4)
policycoreutils-default-encoding (0.1)
protobuf (2.6.1)
pyasn1 (0.1.6)
pycparser (2.14)
pycups (1.9.63)
pycurl (7.19.0)
pydot2 (1.0.33)
pygobject (3.14.0)
pygpgme (0.3)
pyinotify (0.9.4)
pykickstart (1.99.66.6)
pyliblzma (0.5.3)
pyOpenSSL (0.13.1)
pyparsing (1.5.6)
pyparted (3.9)
pysmbc (1.0.13)
python-augeas (0.5.0)
python-bugzilla (1.2.2)
python-dateutil (1.5)
python-default-encoding (0.1)
python-dmidecode (3.10.13)
python-engineio (0.8.7)
python-fedora (0.6.4)
python-ldap (2.4.15)
python-meh (0.25.2)
python-nss (0.16.0)
python-socketio (1.0)
python-yubico (1.2.3)
pytz (2012d)
pyudev (0.15)
pyusb (1.0.0b1)
pyxattr (0.5.1)
pyxdg (0.25)
qrcode (5.0.1)
redhat-access-insights (1.0.6)
requests (2.6.0)
rhnlib (2.5.65)
rhsm (1.15.4)
rpkg (1.35)
rtslib-fb (2.1.57)
scikit-image (0.11.3)
scipy (0.17.0)
seobject (0.1)
sepolicy (1.1)
setroubleshoot (1.1)
setuptools (19.7)
simplejson (3.3.3)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
smmap (0.8.1)
SSSDConfig (1.13.0)
tables (3.2.0rc3)
targetcli-fb (2.1.fb41)
Tempita (0.5.1)
urlgrabber (3.10)
urllib3 (1.10.2)
urwid (1.1.1)
Werkzeug (0.11.3)
WTForms (2.1)
yum-langpacks (0.4.2)
yum-metadata-parser (1.1.4)

0
0
	Luke Yeager 	
Feb 4
For one thing, your version of Flask-SocketIO is too new (2.0 vs 0.6.0).

https://github.com/NVIDIA/DIGITS/blob/digits-3.0/requirements.txt
- show quoted text -
0
0
	Saverio De Vito 	
Feb 4
Thank you for your prompt reply I will downgrade and report...
Thanks again
- show quoted text -
0
0
	Saverio De Vito 	
Feb 4
Translate message to English  
It works now.
Thank you,
saverio
- show quoted text -
0
0

**Comment by SevenGong** [comment] 2016-08-08 07:11
@gheinrich It did work as you said. It is amazing. Thank you very much!

**Comment by SevenGong** [comment] 2016-08-08 07:14
@rjgowth11  Thank you. But I have solved the problem when I used the standard python rather than anaconda as gheinrich said above.

**Comment by gheinrich** [comment] 2016-08-08 08:28
Thanks for the feedback - closing this issue now.

**Closed by gheinrich** 2016-08-08 08:28 UTC
